### ISSUE TITLE
IHADSS helmet for US Airborne pilot loadout

### ISSUE THREAD

**Issue by DrJaffas22** [PXG-Arma/Templates#27]

**Comment by Leubzo** [comment]
Can't get it to equip using addHeadgear or linkItem, and the helmet can't be equipped at the same time as any NVGs and vice versa. Tried removing NVGs from pilot role but still not equipping.

**Comment by DrJaffas22** [comment]
Seen thank you possible alternate to either not clear inventory of apache on spawn or to add 2x ihadss to the apache inventory on spawn?
